### PR TITLE
#6 issue

### PR DESCRIPTION
**Pull request by mehrdadbn9**
#6

### CODE REVIEW

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Hey,

Please revert changes from `CHANGELOG`.md `and releases.json`

**Comment by mehrdadbn9** [comment]
by the way, i assign issue with # (#6), what else i should do?

**Review by Pradumnasaraf — CHANGES_REQUESTED** [review]
Changes are still reflected, please completely revere them.

**Review by mehrdadbn9 — COMMENTED** [review]
i revert that  two file you've said 
i appreciate your kindness for helping

**Comment by Pradumnasaraf** [comment]
> i revert that two file you've said i appreciate your kindness for helping

Hey, I aks to revert your changes from the not the file!

**Comment by Pradumnasaraf** [comment]
Hey, do you need any help fixing the PR?

**Comment by Pradumnasaraf** [comment]
Are you still working on this issue @mehrdadbn9?

**Pull request closed without merging**
