### PR TITLE
Update 3 actions to latest version

### PR DESCRIPTION
**Pull request by ShanmukhiKairuppala**
## ✔️ Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## 📷 Screenshots

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
Hey,

You created PR without getting the issue assigned and approved, which is a violation of CONTRIBUTING guidelines. First, get an issue assigned to you and then raise a PR. I am accepting for this time.

**Review by Pradumnasaraf — APPROVED** [review]
Ah, I just saw you have commented on the issue. But remember to get assigned before creating a PR. Merging for this time.

**Comment by ShanmukhiKairuppala** [comment]
Sorry sir , will wait until i get assigned with the issue.

**Comment by Pradumnasaraf** [comment]
> Sorry sir , will wait until i get assigned with the issue.

Nothing to say sorry. We all are learning

**Comment by ShanmukhiKairuppala** [comment]
Is it mandatory to delete the branch i have created?

**Comment by Pradumnasaraf** [comment]
> Is it mandatory to delete the branch i have created?

It's on you. But it's a good practice to clean up by deleting the branch once it gets merged.

**Comment by ShanmukhiKairuppala** [comment]
ok sir .Thankyou!

**Pull request merged**
